<?php

namespace AdminBundle\Repository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;
use AdminBundle\Entity\Management;


class ManagementRepository extends EntityRepository
{
    public function index()
    {
        $em = $this->getEntityManager();
        $managements = $em->createQueryBuilder()
            ->from('AdminBundle:Management','m')
            ->leftJoin('AdminBundle:User','u','WITH','m.refOwnerId = u.id')
            ->select('m', 'u.username')
            ->getQuery()
            ->getResult();
         ;

        return $managements;
    }
}

//
//$query = $this->createQueryBuilder('c')
//    ->select('c')
//    ->leftJoin('MyBundleName:ChildOne', 'co', 'WITH', 'co.id = c.id')
//    ->leftJoin('MyBundleName:ChildTwo', 'ct', 'WITH', 'ct.id = c.id')
//    ->orderBy('c.createdAt', 'DESC')
//    ->where('co.group = :group OR ct.group = :group')
//    ->setParameter('group', $group)
//    ->setMaxResults(20);


//->from('Project\Entities\Item', 'i')
//    ->select("i, e")
//    ->join("i.entity", 'e')
//    ->where("i.lang = :lang AND e.album = :album")
//    ->setParameter('lang', $lang)
//    ->setParameter('album', $album);