management_index:
    path:     /
    defaults: { _controller: "AdminBundle:Management:index" }
    methods:  GET

management_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Management:show" }
    methods:  GET

management_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Management:new" }
    methods:  [GET, POST]

management_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Management:edit" }
    methods:  [GET, POST]

management_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Management:delete" }
    methods:  DELETE
